---
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      pip-major:
        update-types:
          - "major"
      pip-minor-patch:
        update-types:
          - "minor"
          - "patch"
    target-branch: "develop"
    labels:
      - "dependabot"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions-major:
        update-types:
          - "major"
      actions-minor-patch:
        update-types:
          - "minor"
          - "patch"
    target-branch: "develop"
    labels:
      - "dependabot"
      - "github actions"
