repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    - id: check-added-large-files
    - id: check-merge-conflict
      args: ["--assume-in-merge"]
    - id: check-toml
    - id: check-yaml
    - id: debug-statements
    - id: detect-aws-credentials
      args:
      - --allow-missing-credentials
    - id: detect-private-key
    - id: end-of-file-fixer
    - id: name-tests-test
      args: ["--pytest-test-first"]
    - id: no-commit-to-branch  # Protects main by default
    - id: trailing-whitespace

  - repo: https://github.com/kynan/nbstripout
    rev: 0.9.1
    hooks:
    - id: nbstripout

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.1
    hooks:
    - id: ruff-check  # Linter
      args: [--fix]
    - id: ruff-format  # Formatter

  - repo: https://github.com/crate-ci/typos
    rev: v1.48.0
    hooks:
    - id: typos
      name: Commit message typos
      args: []  # Turns off automatic fixing
      stages: [commit-msg]
    - id: typos
      name: Script typos
      args: []  # Turns off automatic fixing
      stages: [pre-commit]

#  - repo: https://github.com/gitleaks/gitleaks
#    rev: v8.30.1
#    hooks:
#    - id: gitleaks

  - repo: local
    hooks:
      - id: restricted-filenames
        name: Restricted filenames
        entry: These file extensions are restricted. Data should be removed from the commit
        language: fail
        files: .*\.(arvo|bson|csv|dat|fbs|feather|h5|hd|hdf5|ndjson|orc|parquet|proto|sav|tsv|xls|xlsx|xml)
