[run_spec]
#Session size can be s, m, l or xl
spark_session_size =

[filepaths]
# df1_path, df2_path and df_candidates_path must be parquet files
# checkpoint_path must specify a unique folder location as the folder will be deleted at the end of the run
bucket_name =
ssl_file =
df1_path =
df2_path =
df_candidates_path =
checkpoint_path =
output_path =

[variables]
df1_id =
df2_id =
linkage_vars =
df1_suffix =
df2_suffix =

[cutpoints]
# Ensure all variables in linkage_vars have a config here - these examples show when this is:
# linkage_vars = day, month, year, sex, surname
# Add the configs as individual cutpoints, like this:
# surname_cutpoints = 0.8, 1.0
# If a variable is not a string variable (and so does not have cutpoints), format like this:
# sex_cutpoint = None
day_cutpoints =
month_cutpoints =
year_cutpoints =
sex_cutpoints =
surname_cutpoints =
