name: Deploy version to Test PyPI

on: 
  workflow_dispatch:
    inputs:
      tags:
        description: "Version to deploy, e.g. 1.0.0"
        required: true
        type: string

jobs:
  release-build:
    name: Build and verify release distributions
    runs-on: ubuntu-latest
    permissions:
      # allows the provenance attestation to work
      attestations: write
      id-token: write
    steps:
      - name: Check out repository
        id: build-repo-checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - name: Build and lint dist
        id: build-dist
        uses: hynek/build-and-inspect-python-package@2abe76da66d0a6a4a227101f9348ee855797cfa5
        with:
          attest-build-provenance-github: 'true'
  
  release-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    needs: release-build
    permissions:
      # mandatory for PyPI Trusted Publishing
      id-token: write
    environment:
      name: test-pypi
      url: https://test.pypi.org/project/scalelink/
    steps:
      - name: Retrieve release distributions
        id: publish-retrieve-dist
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c
        with:
          name: release-dists
          path: dist/

      - name: Publish release distributions on PyPI
        id: publish-to-pypi
        uses: pypa/gh-action-pypi-publish@dc37677b2e1c63e2034f94d8a5b11f265b73ba33
        with:
          repository-url: https://test.pypi.org
