name: Deploy PyPI workflow

on:
  push:
    branches:
      - main

jobs:
  # Build and lint release distributions
  release-build:
    name: Build and verify release distributions
    runs-on: ubuntu-latest
    permissions:
      # allows the provenance attestation to work
      attestations: write
      id-token: write
    steps:
      - name: Check out repository
        id: build-repo-checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          python-version: ["3.10", "3.11"]

      - name: Build and lint dist
        id: build-dist
        uses: hynek/build-and-inspect-python-package@v2
        with:
          attest-build-provenance-github: 'true'
  
  # Publish to PyPI
  release-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    needs: release-build
    permissions:
      # mandatory for PyPI Trusted Publishing
      id-token: write
    environment:
      name: pypi
    steps:
      - name: Retrieve release distributions
        id: publish-retrieve-dist
        uses: actions/download-artifact@v5
        with:
          name: release-dists
          path: dist/

      - name: Publish release distributions on PyPI
        id: publish-to-pypi
        uses: pypa/gh-action-pypi-publish@release/v1
