name: "Increment version workflow"

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Extract package version
        id: package_version
        run: |
          echo "PACKAGE_VERSION=$python setup.py --version)" >> $GITHUB_ENV
      
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ env.PACKAGE_VERSION }}
      
